#!/bin/bash
# Clone upstream ChkTeX, build the C oracle binary, and wire oracle tests.
#
# Usage:
#   ./tools/setup-oracle.sh              # clone/build at /tmp/chktex-upstream
#   ./tools/setup-oracle.sh --run-tests  # build, then run the oracle suite
#   CHKTEX_UPSTREAM_PARENT=$HOME/.cache/chktex-oracle ./tools/setup-oracle.sh
#
# After setup:
#   source target/oracle.env
#   ./tools/run-oracle-tests.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/target/oracle.env"

UPSTREAM_URL="${CHKTEX_UPSTREAM_URL:-https://git.savannah.nongnu.org/git/chktex.git}"
UPSTREAM_PARENT="${CHKTEX_UPSTREAM_PARENT:-/tmp/chktex-upstream}"
UPSTREAM_COMMIT="${CHKTEX_UPSTREAM_COMMIT:-b0c5352bd775136b7777356067f8726919cc9043}"
REPO_DIR="$UPSTREAM_PARENT/chktex"
BUILD_DIR="$REPO_DIR/chktex"
ORACLE="$BUILD_DIR/chktex"

RUN_TESTS=0
FORCE=0
PIN_COMMIT=1

usage() {
    cat <<EOF
Usage: $(basename "$0") [options]

Clone upstream ChkTeX, build the legacy C binary, and write target/oracle.env
so the Rust oracle test suite can compare against it.

Options:
  --parent DIR     Install root (default: /tmp/chktex-upstream)
  --commit HASH    Upstream git commit to checkout (default: audited baseline)
  --no-pin         Use the latest upstream HEAD instead of the pinned commit
  --url URL        Upstream git remote (default: Savannah chktex.git)
  --force          Re-run configure/make even if the oracle binary exists
  --run-tests      Run ./tools/run-oracle-tests.sh after a successful build
  -h, --help       Show this help

Environment:
  CHKTEX_UPSTREAM_PARENT   Same as --parent
  CHKTEX_UPSTREAM_COMMIT   Same as --commit
  CHKTEX_UPSTREAM_URL      Same as --url

Outputs:
  Oracle binary:  \$CHKTEX_ORACLE      -> $ORACLE
  Fixture dir:    \$CHKTEX_UPSTREAM_DIR -> $BUILD_DIR
  Env file:       $ENV_FILE
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --parent)
            UPSTREAM_PARENT="$2"
            REPO_DIR="$UPSTREAM_PARENT/chktex"
            BUILD_DIR="$REPO_DIR/chktex"
            ORACLE="$BUILD_DIR/chktex"
            shift 2
            ;;
        --commit)
            UPSTREAM_COMMIT="$2"
            PIN_COMMIT=1
            shift 2
            ;;
        --no-pin)
            PIN_COMMIT=0
            shift
            ;;
        --url)
            UPSTREAM_URL="$2"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        --run-tests)
            RUN_TESTS=1
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "error: required command not found: $1" >&2
        exit 1
    fi
}

require_build_tools() {
    require_cmd git
    require_cmd gcc
    require_cmd make
    require_cmd perl

    if [[ ! -x "$BUILD_DIR/configure" ]]; then
        for tool in autoconf automake aclocal autoheader; do
            require_cmd "$tool"
        done
    fi
}

clone_or_update() {
    mkdir -p "$UPSTREAM_PARENT"

    if [[ -d "$REPO_DIR/.git" ]]; then
        echo ">>> Updating existing clone at $REPO_DIR"
        git -C "$REPO_DIR" fetch --tags origin
    else
        echo ">>> Cloning upstream from $UPSTREAM_URL"
        git clone "$UPSTREAM_URL" "$REPO_DIR"
    fi

    if [[ "$PIN_COMMIT" -eq 1 ]]; then
        echo ">>> Checking out compatibility baseline $UPSTREAM_COMMIT"
        git -C "$REPO_DIR" checkout --detach "$UPSTREAM_COMMIT"
    else
        echo ">>> Checking out latest upstream HEAD"
        git -C "$REPO_DIR" checkout --detach origin/HEAD
    fi
}

build_oracle() {
    if [[ -x "$ORACLE" && "$FORCE" -eq 0 ]]; then
        echo ">>> Oracle binary already exists at $ORACLE (use --force to rebuild)"
        return 0
    fi

    echo ">>> Building upstream oracle in $BUILD_DIR"
    cd "$BUILD_DIR"

    if [[ ! -x ./configure ]]; then
        echo ">>> Running autogen.sh"
        ./autogen.sh
    fi

    echo ">>> Running configure"
    ./configure --enable-pcre=no LIBS=-lncurses

    echo ">>> Running make"
    make -j"$(nproc)"

    if [[ ! -x "$ORACLE" ]]; then
        echo "error: build finished but oracle binary is missing: $ORACLE" >&2
        exit 1
    fi
}

write_env_file() {
    local resolved_commit
    resolved_commit="$(git -C "$REPO_DIR" rev-parse HEAD)"

    mkdir -p "$ROOT/target"
    cat >"$ENV_FILE" <<EOF
# Generated by tools/setup-oracle.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
export CHKTEX_ORACLE="$ORACLE"
export CHKTEX_UPSTREAM_DIR="$BUILD_DIR"
export CHKTEX_UPSTREAM_COMMIT="$resolved_commit"
EOF
    echo ">>> Wrote $ENV_FILE"
}

verify_oracle() {
    if [[ ! -f "$BUILD_DIR/Test.tex" ]]; then
        echo "error: upstream fixture Test.tex not found in $BUILD_DIR" >&2
        exit 1
    fi

    echo ">>> Oracle version:"
    "$ORACLE" --version 2>&1 | sed '/Could not find global resource file/d'
}

print_next_steps() {
    cat <<EOF

Oracle setup complete.

  CHKTEX_ORACLE=$ORACLE
  CHKTEX_UPSTREAM_DIR=$BUILD_DIR

Load the env file in your shell:

  source target/oracle.env

Run the differential test suite:

  ./tools/run-oracle-tests.sh

Compare warning output on Test.tex:

  ./tools/diff-warnings.sh "\$CHKTEX_UPSTREAM_DIR/Test.tex"
EOF
}

main() {
    require_build_tools
    clone_or_update
    build_oracle
    write_env_file
    verify_oracle
    "$ROOT/tools/generate-upstream-config-fixtures.sh" "$BUILD_DIR"
    print_next_steps

    if [[ "$RUN_TESTS" -eq 1 ]]; then
        echo
        echo ">>> Running oracle test suite"
        "$ROOT/tools/run-oracle-tests.sh"
    fi
}

main "$@"
